# Generated by Django 5.2.17 on 2026-08-26

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("login_api", "0002_add_preflight_statuses"),
    ]

    operations = [
        migrations.AlterField(
            model_name="connectionrequest",
            name="status",
            field=models.CharField(
                choices=[
                    ("ready", "Ready"),
                    ("invalid", "Invalid"),
                    ("duplicate", "Duplicate"),
                    ("skipped", "Skipped"),
                    ("checking", "Checking"),
                    ("pending", "Pending"),
                    ("connected", "Connected"),
                    ("sending", "Sending"),
                    ("sent", "Sent"),
                    ("failed", "Failed"),
                    ("accepted", "Accepted"),
                ],
                max_length=20,
            ),
        ),
    ]
