# Generated by Django 5.2.17 on 2026-08-26 13:59

import django.db.models.deletion
import uuid
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_api', '0003_add_skipped_status'),
    ]

    operations = [
        migrations.CreateModel(
            name='Invitation',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('checking', 'Checking'), ('sending', 'Sending'), ('pending', 'Pending'), ('accepted', 'Accepted'), ('already_connected', 'Already connected'), ('failed', 'Failed'), ('needs_review', 'Needs review'), ('cancelled', 'Cancelled')], default='queued', max_length=32)),
                ('error', models.TextField(blank=True)),
                ('provider_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('accepted_at', models.DateTimeField(blank=True, null=True)),
                ('checked_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='MessageTemplate',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(default='Follow-up', max_length=100)),
                ('body', models.TextField()),
                ('is_active', models.BooleanField(default=False)),
                ('auto_send_enabled', models.BooleanField(default=False)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.CreateModel(
            name='Person',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('name', models.CharField(max_length=255)),
                ('linkedin_url', models.URLField(blank=True, max_length=500)),
                ('public_id', models.CharField(max_length=255)),
                ('normalized_public_id', models.CharField(max_length=255, unique=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['name', 'normalized_public_id'],
            },
        ),
        migrations.AddField(
            model_name='connectionimport',
            name='auto_message_enabled',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='invitation',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='login_api.invitation'),
        ),
        migrations.CreateModel(
            name='Message',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('body', models.TextField()),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('sending', 'Sending'), ('sent', 'Sent'), ('failed', 'Failed'), ('needs_review', 'Needs review'), ('cancelled', 'Cancelled')], default='queued', max_length=32)),
                ('error', models.TextField(blank=True)),
                ('provider_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('queued_at', models.DateTimeField(blank=True, null=True)),
                ('sent_at', models.DateTimeField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
                ('invitation', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='message', to='login_api.invitation')),
                ('template', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='messages', to='login_api.messagetemplate')),
            ],
            options={
                'ordering': ['-updated_at'],
            },
        ),
        migrations.AddField(
            model_name='connectionimport',
            name='message_template',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='connection_imports', to='login_api.messagetemplate'),
        ),
        migrations.AddField(
            model_name='invitation',
            name='person',
            field=models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, related_name='invitation', to='login_api.person'),
        ),
        migrations.AddField(
            model_name='connectionrequest',
            name='person',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='import_rows', to='login_api.person'),
        ),
        migrations.CreateModel(
            name='WorkItem',
            fields=[
                ('id', models.UUIDField(default=uuid.uuid4, editable=False, primary_key=True, serialize=False)),
                ('kind', models.CharField(choices=[('send_invitation', 'Send invitation'), ('check_acceptances', 'Check acceptances'), ('send_message', 'Send message')], max_length=32)),
                ('status', models.CharField(choices=[('queued', 'Queued'), ('running', 'Running'), ('succeeded', 'Succeeded'), ('failed', 'Failed'), ('needs_review', 'Needs review'), ('cancelled', 'Cancelled')], default='queued', max_length=32)),
                ('dedupe_key', models.CharField(blank=True, max_length=255, null=True, unique=True)),
                ('due_at', models.DateTimeField()),
                ('attempt_count', models.PositiveIntegerField(default=0)),
                ('error', models.TextField(blank=True)),
                ('provider_status', models.PositiveSmallIntegerField(blank=True, null=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('started_at', models.DateTimeField(blank=True, null=True)),
                ('completed_at', models.DateTimeField(blank=True, null=True)),
                ('invitation', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='login_api.invitation')),
                ('message', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='work_items', to='login_api.message')),
            ],
            options={
                'ordering': ['due_at', 'created_at'],
                'indexes': [models.Index(fields=['status', 'due_at'], name='login_api_w_status_0abf1f_idx')],
            },
        ),
    ]
