# Generated by Django 5.2.17 on 2026-08-26 14:14

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('login_api', '0005_backfill_people_and_invitations'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionimport',
            name='message_template_body',
            field=models.TextField(blank=True),
        ),
    ]
