# Generated by Django 5.2.17 on 2026-08-26 15:26

from django.db import migrations, models


def keep_one_template(apps, schema_editor):
    MessageTemplate = apps.get_model("login_api", "MessageTemplate")
    template = (
        MessageTemplate.objects.filter(is_active=True)
        .order_by("-updated_at")
        .first()
        or MessageTemplate.objects.order_by("-updated_at").first()
    )
    if template is None:
        return
    MessageTemplate.objects.exclude(pk=template.pk).delete()
    MessageTemplate.objects.filter(pk=template.pk).update(is_active=True)


class Migration(migrations.Migration):

    dependencies = [
        ('login_api', '0006_connectionimport_message_template_body'),
    ]

    operations = [
        migrations.AddField(
            model_name='connectionimport',
            name='message_delay_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.AddField(
            model_name='messagetemplate',
            name='delay_minutes',
            field=models.PositiveIntegerField(default=5),
        ),
        migrations.RunPython(keep_one_template, migrations.RunPython.noop),
    ]
